# ==============================
# SERVER
# ==============================
server.port=8080

# ==============================
# DATABASE (MySQL)
# ==============================
#spring.datasource.url=jdbc:mysql://localhost:3306/traffic_monitoring?useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=2505
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# H2 DATABASE (for deployment)
server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# JWT CONFIG
# ==============================
jwt.secret=SmartTrafficSystem_UltraSecretKey_2024!@#$%^&*()
jwt.expiration=86400000

# ==============================
# STATIC FILES (FRONTEND)
# ==============================
spring.web.resources.static-locations=classpath:/static/
